### ISSUE TITLE
Issue: "Kudo All!" Button Not Working on Microsoft Edge and Google Chrome

### ISSUE THREAD

**Issue by cgaz90** [cankut/autokudo#1]
Description:
I am experiencing an issue with the "Kudo All!" button on the extension, similar to the feedback from another user on the Chrome Store page. When I click the "Kudo All!" button or wait for the timer, no kudos are given. The extension appears to function normally, but after refreshing the Strava Dashboard, none of the activities of athletes I follow have received kudos.

Steps to Reproduce:

1. Open Strava Dashboard.
2. Click the "Kudo All!" button.
3. Wait for the timer to complete.
4. Refresh the Strava Dashboard.

Expected Result:
Activities of athletes I follow should receive kudos.

Actual Result:
No kudos are given, even though the extension behaves as if it is working.

Details:

Extension Version: 1.1
Browser: Microsoft Edge
Browser Version:  126.0.2592.24

Additional Information:
Here is a similar report from another user on the Chrome Store page:

"Just noticed today that no kudos are given when clicking the "Kudo All!" button, nor waiting out the timer. The extension appears to behave normally, but when I refresh the Strava Dashboard, none of the activities of athletes I follow have received kudos from me. ☹
I'm using version 1.1 on Chrome version 124.0.6367.208"

Please investigate this issue.

**Comment by cankut** [comment]
@cgaz90 Strava seems to have changed its feed API. There is a mismatch between the old time format and the new time format being used.

This should be fixed in the next release (v1.2) of the extension.

By the way, I have never tried this extension with Microsoft Edge. I had no idea it was even compatible with MS Edge until now.

**Comment by cgaz90** [comment]
@cankut Thanks for the prompt response and for identifying the issue with Strava's feed API changes. It's great to know that there’s a v1.2 on the way that addresses this issue!

Regarding compatibility with Microsoft Edge, I can confirm that it works the same as in Chrome in my experience.

I appreciate your efforts.

**Comment by cankut** [comment]
Version 1.2 is published in the Chrome Web Store

https://chromewebstore.google.com/detail/strava-auto-kudo/bpdlomdbmhipfcjacpgpnhbnckhiipdh
